actors:
  rihoyan:
    image_url: /images/actors/rihoyan.jpg
    name: りほやん
    url: https://twitter.com/rllllho
  risacan:
    image_url: /images/actors/risacan.jpg
    name: りさきゃん
    url: https://twitter.com/_risacan_
  tantan:
    image_url: /images/actors/tantan.jpg
    name: たんたん
    url: https://twitter.com/ayanotango
  kiripon:
    image_url: /images/actors/kiripon.jpg
    name: きりぽん
    url: https://twitter.com/krk85y
  kasumi:
    image_url: /images/actors/kasumi.jpg
    name: かすみ
    url: https://twitter.com/kasumi8pon
  mami_inuzuka:
    image_url: /images/actors/mami_inuzuka.jpg
    name: いぬづかまみ
    url: https://twitter.com/mami_inuzuka
  maf:
    image_url: /images/actors/maf.jpg
    name: maf
    url: https://twitter.com/_maf_u_
author: yancanfm
description: エンジニアめっちゃ楽しい
description_long: りほやんとりさきゃんが今気になるテック系の話題を話したり話さなかったりするポッドキャスト
? email
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-128113879-1
hashtag: yancanfm
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: yancan.fm
url: https://www.yancan.tech
